model_list:
  - model_name: claude-sonnet-4.5-pplx-litellm
    litellm_params:
      model: perplexity/claude-sonnet-4.5
      api_key: os.environ/PERPLEXITY_API_KEY

litellm_settings:
  # Sets the master key for the proxy
  master_key: os.environ/LITELLM_MASTER_KEY
