general_settings:
  host: 0.0.0.0
  port: 10000

model_list:
  - model_name: claude-sonnet-4.5-pplx-litellm
    litellm_params:
      model: perplexity/claude-sonnet-4.5
      api_key: os.environ/PERPLEXITY_API_KEY

router_settings:
  enable_models_list: True
